name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: |
        A="BBB"
        echo "::group::${A}\n"
        ls
        pwd
        uname -a
        echo "::endgroup::\n"
    - name: Checkout code
      run: |
        A="CCC"
        echo "::group::${A}\n"
        ls
        pwd
        uname -a
        echo "::endgroup::\n"
