name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: |
        A="BBB"
        echo -e "::group::${A}\n"
        ls
        pwd
        uname -a
        echo -e "::endgroup::\n"
        A="CCC"
        echo -e "::group::${A}\n"
        ls
        pwd
        uname -a
        echo -e "::endgroup::\n"
