name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: |
        wget https://github.com/aquasecurity/tfsec/releases/download/v1.28.0/tfsec-linux-amd64
        ./tfsec-linux-amd64 --version
        A="BBB"
        echo "::group::${A}"
        ls
        pwd
        uname -a
        echo "::endgroup::"
        A="CCC"
        echo "::group::${A}"
        ls
        pwd
        uname -a
        echo "::endgroup::"
